version: '3.1'
services:
  pgadmin:
    image: dpage/pgadmin4
    ports:
      - "5050:80"
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@icgroup.com
      PGADMIN_DEFAULT_PASSWORD: admin
    volumes:
      - ./servers.json:/pgadmin4/servers.json

