apiVersion: v1
kind: Namespace
metadata:
  name: odoo-pgadmin

---

apiVersion: v1
kind: ConfigMap
metadata:
  name: odoo-config
  namespace: odoo-pgadmin
data:
  POSTGRES_HOST: odoo-db
  POSTGRES_PORT: "5432"
  POSTGRES_USER: odoo
  POSTGRES_PASSWORD: odoo_password
  POSTGRES_DB: odoo

---

apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: odoo-data-pvc
  namespace: odoo-pgadmin
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 5Gi

---

apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: pgadmin-data-pvc
  namespace: odoo-pgadmin
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi

---

apiVersion: apps/v1
kind: Deployment
metadata:
  name: odoo
  namespace: odoo-pgadmin
spec:
  replicas: 1
  selector:
    matchLabels:
      app: odoo
  template:
    metadata:
      labels:
        app: odoo
    spec:
      containers:
      - name: odoo
        image: odoo:16
        ports:
        - containerPort: 8069
        envFrom:
        - configMapRef:
            name: odoo-config
        volumeMounts:
        - name: odoo-data
          mountPath: /var/lib/odoo
      volumes:
      - name: odoo-data
        persistentVolumeClaim:
          claimName: odoo-data-pvc

---

apiVersion: v1
kind: Service
metadata:
  name: odoo
  namespace: odoo-pgadmin
spec:
  selector:
    app: odoo
  ports:
    - protocol: TCP
      port: 8069
      targetPort: 8069
  type: NodePort

---

apiVersion: apps/v1
kind: Deployment
metadata:
  name: pgadmin
  namespace: odoo-pgadmin
spec:
  replicas: 1
  selector:
    matchLabels:
      app: pgadmin
  template:
    metadata:
      labels:
        app: pgadmin
    spec:
      containers:
      - name: pgadmin
        image: dpage/pgadmin4:latest
        ports:
        - containerPort: 80
        env:
        - name: PGADMIN_DEFAULT_EMAIL
          value: admin@example.com
        - name: PGADMIN_DEFAULT_PASSWORD
          value: pgadmin_password
        volumeMounts:
        - name: pgadmin-data
          mountPath: /var/lib/pgadmin
      volumes:
      - name: pgadmin-data
        persistentVolumeClaim:
          claimName: pgadmin-data-pvc

---

apiVersion: v1
kind: Service
metadata:
  name: pgadmin
  namespace: odoo-pgadmin
spec:
  selector:
    app: pgadmin
  ports:
    - protocol: TCP
      port: 5050
      targetPort: 80
  type: NodePort

---

apiVersion: apps/v1
kind: Deployment
metadata:
  name: odoo-db
  namespace: odoo-pgadmin
spec:
  replicas: 1
  selector:
    matchLabels:
      app: odoo-db
  template:
    metadata:
      labels:
        app: odoo-db
    spec:
      containers:
      - name: postgres
        image: postgres:13
        ports:
        - containerPort: 5432
        env:
        - name: POSTGRES_USER
          value: odoo
        - name: POSTGRES_PASSWORD
          value: odoo_password
        - name: POSTGRES_DB
          value: odoo
        volumeMounts:
        - name: postgres-data
          mountPath: /var/lib/postgresql/data
      volumes:
      - name: postgres-data
        persistentVolumeClaim:
          claimName: odoo-data-pvc

---

apiVersion: v1
kind: Service
metadata:
  name: odoo-db
  namespace: odoo-pgadmin
spec:
  selector:
    app: odoo-db
  ports:
    - protocol: TCP
      port: 5432
      targetPort: 5432
  clusterIP: None # Headless service for internal communication
