apiVersion: v1
kind: Namespace
metadata:
  name: icgroup
  labels:
    env: prod

---

apiVersion: apps/v1
kind: Deployment
metadata:
  name: pgadmin-deployment
  namespace: icgroup
  labels:
    app: pgadmin
    env: prod
spec:
  replicas: 1
  selector:
    matchLabels:
      app: pgadmin
  template:
    metadata:
      labels:
        app: pgadmin
    spec:
      containers:
      - name: pgadmin
        image: dpage/pgadmin4:latest
        ports:
        - containerPort: 80
        env:
        - name: PGADMIN_DEFAULT_EMAIL
          value: "purtisngos@gmail.com"
        - name: PGADMIN_DEFAULT_PASSWORD
          value: "admin123" 
        volumeMounts:
        - name: pgadmin-data
          mountPath: /var/lib/pgadmin
        - name: servers-json
          mountPath: /pgadmin4/servers.json
          subPath: servers.json
      volumes:
      - name: pgadmin-data
        persistentVolumeClaim:
          claimName: pgadmin-pvc
      - name: servers-json
        configMap:
          name: pgadmin-config

---

apiVersion: v1
kind: Service
metadata:
  name: pgadmin-service
  namespace: icgroup
  labels:
    app: pgadmin
    env: prod
spec:
  selector:
    app: pgadmin
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
  type: NodePort # Peut être changé en LoadBalancer pour un environnement cloud

---

apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: pgadmin-pvc
  namespace: icgroup
  labels:
    app: pgadmin
    env: prod
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 5Gi

---

apiVersion: v1
kind: ConfigMap
metadata:
  name: pgadmin-config
  namespace: icgroup
  labels:
    app: pgadmin
    env: prod
data:
  servers.json: |
    {
        "Servers": {
            "1": {
                "Name": "Odoo Database",
                "Group": "Odoo",
                "Host": "odoo-postgres-service",
                "Port": 5432,
                "MaintenanceDB": "postgres",
                "Username": "odoo_user",
                "SSLMode": "prefer",
                "PassFile": "/var/lib/pgadmin/pgpassfile"
            }
        }
    }
