# roles/pgadmin_role/tasks/main.yml
---
- name: Create Docker network for PgAdmin
  docker_network:
    name: "{{ pgadmin_network_name }}"
    state: present

- name: Create Docker volume for PgAdmin data
  docker_volume:
    name: "{{ pgadmin_volume_name }}"
    state: present

- name: Run PgAdmin container
  docker_container:
    name: "{{ pgadmin_container_name }}"
    image: "dpage/pgadmin4:{{ pgadmin_version }}"
    state: started
    restart_policy: unless-stopped
    env:
      PGADMIN_DEFAULT_EMAIL: "{{ pgadmin_email }}"
      PGADMIN_DEFAULT_PASSWORD: "{{ pgadmin_password }}"
    volumes:
      - "{{ pgadmin_volume_name }}:/var/lib/pgadmin"
    networks:
      - "{{ pgadmin_network_name }}"
    ports:
      - "5050:80"
    detach: true
